<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'Adakah anda pasti mahu memadamkan item ini?',
    'Back' => 'Kembali',
    'Class {class} has no param called "{param}."' => 'kelas {class} tidak mempunyai param yang dipanggil "{param}."',
    'Clone' => 'Clone',
    'Create' => 'Buat',
    'Delete' => 'Padam',
    'Home' => 'Rumah',
    'Login' => 'Log masuk',
    'Reset' => 'Tetapkan semula',
    'Reset filter' => 'Tetapkan semula penapis',
    'Save' => 'Simpan',
    'Sign In' => 'Masuk',
    'Update' => 'Kemas kini',
    'View' => 'Lihat',
    '{icon} Lock Screen' => '{icon} Skrin kunci',
    '{icon} Log Out' => '{icon} Keluar',
    '{icon} My Calendar' => '{icon} Kalendar saya',
    '{icon} My Inbox {badge}' => '{icon} Peti Masuk Saya {badge}',
    '{icon} My Profile' => '{icon} Profil Saya',
    '{icon} My Tasks {badge}' => '{icon} Tugas saya {badge}',
];
