<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'Apakah Anda yakin ingin menghapus item ini?',
    'Back' => 'Kembali',
    'Class {class} has no param called "{param}."' => 'Kelas {class} tidak memiliki param yang disebut "{param}."',
    'Clone' => 'Klon',
    'Create' => 'Buat',
    'Delete' => 'Hapus',
    'Home' => 'Beranda',
    'Login' => 'Masuk',
    'Reset' => 'Setel ulang',
    'Reset filter' => 'Setel ulang menyaring',
    'Save' => 'Simpan',
    'Sign In' => 'Masuk',
    'Update' => 'Pembaruan',
    'View' => 'Lihat',
    '{icon} Lock Screen' => '{icon} Kunci Layar',
    '{icon} Log Out' => '{icon} Keluar',
    '{icon} My Calendar' => '{icon} Kalender Saya',
    '{icon} My Inbox {badge}' => '{icon} Kotak Masuk Saya {badge}',
    '{icon} My Profile' => '{icon} Profil Saya',
    '{icon} My Tasks {badge}' => '{icon} Tugas Saya {badge}',
];
